# list1 = ["I", "love", "Python"]
# joined = ",".join(list1)
# a = '-'.join("abcdefj")
# print(joined)
# print(a)
# b = 'iuuweqw98r7 78937 rsu!'
# c = b.strip("!")
# print(c)
# d = b.strip('')
# print(d)
text1 = "uieyrqioudfhaj"
text2 = text1.find("e")
print(text2)
print(ord("q"))
print(ord("w"))
print(ord("e"))
print(ord("r"))
print(ord("t"))
print(ord("y"))
print(ord("u"))
print(ord("i"))
print(ord("o"))
print(ord("p"))
print(ord("A"))
print(ord("S"))
print(ord("d"))
print(ord("f"))
print(ord("g"))
print(ord("h"))
print(ord("j"))
print(ord("k"))
print(ord("l"))
print(ord("z"))
print(ord("x"))
print(ord("c"))
print(ord("v"))
print(ord("b"))
print(ord("n"))
print(ord("m"))

